CREATE DATABASE RIKKEICLINICDB;
USE RIKKEICLINICDB;

-- 1. BẢNG BỆNH NHÂN (PATIENTS)
CREATE TABLE PATIENTS (
    PATIENT_ID INT PRIMARY KEY,
    FULL_NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15) UNIQUE NOT NULL,
    DATE_OF_BIRTH DATE
);

-- 7. BẢNG KHO THUỐC (MEDICINES)
CREATE TABLE MEDICINES (
    MEDICINE_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(18,2) NOT NULL,
    STOCK INT NOT NULL DEFAULT 0
);

-- 8. BẢNG CÔNG NỢ BỆNH NHÂN (PATIENT_INVOICES)
CREATE TABLE PATIENT_INVOICES (
    PATIENT_ID INT PRIMARY KEY,
    TOTAL_DUE DECIMAL(18,2) NOT NULL DEFAULT 0,
    LAST_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
);

-- CHÈN BỆNH NHÂN
INSERT INTO PATIENTS (PATIENT_ID, FULL_NAME, PHONE, DATE_OF_BIRTH) VALUES
(1, 'NGUYEN VAN AN', '0901111222', '1990-05-15'),
(2, 'TRAN THI BINH', '0912222333', '1985-08-20'),
(3, 'LE HOANG CUONG', '0923333444', '2000-12-01');

-- CHÈN THUỐC
INSERT INTO MEDICINES (MEDICINE_ID, NAME, PRICE, STOCK) VALUES
(1, 'AMOXICILLIN 500MG', 15000, 100),  -- TỒN KHO NHIỀU
(2, 'PANADOL EXTRA', 5000, 5);         -- TỒN KHO ÍT

-- CHÈN CÔNG NỢ BỆNH NHÂN
INSERT INTO PATIENT_INVOICES (PATIENT_ID, TOTAL_DUE) VALUES
(1, 1500000.00), -- ĐÃ SỬA: NỢ 1.5TR ĐỂ TEST BÀI GIẢI PHÓNG GIƯỜNG BỆNH
(2, 0),
(3, 0);

DELIMITER //
CREATE PROCEDURE SP_DISPENSEMEDICINE(
	IN P_PATIENT_ID INT,
    IN P_MEDICINE_ID INT,
    IN P_QUANTITY INT,
    OUT P_STATUS_MESSAGE VARCHAR(255)
)
BEGIN 
	DECLARE V_STOCK INT;
    DECLARE V_PRICE DECIMAL(18,2);
    DECLARE V_PATIENT_TRANSFER INT;
    
    START TRANSACTION;
    
    -- KIỂM TRA SỰ TỒN TẠI CỦA BỆNH NHÂN
    SELECT COUNT(*) INTO V_PATIENT_TRANSFER FROM PATIENTS WHERE PATIENT_ID = P_PATIENT_ID;
    
	-- LẤY THÔNG TIN THUỐC
    SELECT STOCK, PRICE INTO V_STOCK, V_PRICE FROM MEDICINES 
    WHERE MEDICINE_ID = P_MEDICINE_ID;
    
    IF V_PATIENT_TRANSFER = 0 THEN
		SET P_STATUS_MESSAGE = 'LỖI: BỆNH NHÂN KHÔNG TỒN TẠI';
        ROLLBACK;
	ELSEIF V_STOCK IS NULL THEN
		SET P_STATUS_MESSAGE = 'LỖI: MÃ THUỐC KHÔNG HỢP LỆ';
        ROLLBACK;
	ELSEIF V_STOCK < P_QUANTITY THEN
		SET P_STATUS_MESSAGE = 'LỖI: SỐ LƯỢNG TỒN KHO KHÔNG ĐỦ';
        ROLLBACK;
	ELSE 
		UPDATE MEDICINES
        SET STOCK = STOCK - P_QUANTITY
        WHERE MEDICINE_ID = P_MEDICINE_ID;
        
        UPDATE PATIENT_INVOICES
        SET TOTAL_DUE = TOTAL_DUE + (P_QUANTITY * V_PRICE),
			LAST_UPDATED = CURRENT_TIMESTAMP()
        WHERE PATIENT_ID = P_PATIENT_ID;
        
        COMMIT;
        SET P_STATUS_MESSAGE = 'ĐÃ CẤP PHÁT THÀNH CÔNG';
	END IF;
END //

DELIMITER ;			
    
SET @TESTING = '';

-- Cấp phát hợp lệ
CALL SP_DISPENSEMEDICINE(1, 1, 2, @TESTING);
SELECT @TESTING;

-- Chặn + thông báo lỗi đúng khi dữ liệu số lượng vượt quá tồn kho 
CALL SP_DISPENSEMEDICINE(2, 2, 10, @TESTING);
SELECT @TESTING;
